"""Add raw_code to TestScript

Revision ID: 23d3692ec2eb
Revises: d56b96560fb7
Create Date: 2026-05-30 01:23:03.385230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d3692ec2eb'
down_revision: Union[str, Sequence[str], None] = 'd56b96560fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_scripts', sa.Column('raw_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_scripts', 'raw_code')
    # ### end Alembic commands ###
