"""Add environment credentials

Revision ID: d56b96560fb7
Revises: 
Create Date: 2026-05-30 00:47:07.633100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56b96560fb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('default_username', sa.String(), nullable=True))
    op.add_column('environments', sa.Column('default_password', sa.String(), nullable=True))
    op.add_column('environments', sa.Column('release_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environments', 'release_version')
    op.drop_column('environments', 'default_password')
    op.drop_column('environments', 'default_username')
    # ### end Alembic commands ###
